[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
name = "client"
path = "src/lib.rs"

[dependencies]
tonic = {version = "0.13.1"}
prost = "0.13.5"
tokio = {version="1.45.1",features=["macros","rt-multi-thread","fs"]}
tokio-stream="0.1"
uuid={version="1.10" , features=["v4","serde"]}
chrono = "0.4.41"
log = "0.4.27"
simplelog = "0.12.2"
dotenv = "0.15.0"
serde = {version = "1.0.219", features = ["derive"] }
actix-web = "4.11.0"
actix-multipart = "0.7.2"
futures-util = "0.3.31"
handlers = "0.10.0"
serde_json = "1.0.140"
actix-cors = "0.7.1"
async-stream = "=0.1.2"
bytes = "1.10.1"

[build-dependencies]
tonic-build = "0.13.1"

