version: "3.9"
services:
  server:
    image: ftp-grpc-server
    container_name: ftp-grpc-server
    env_file: ./server/.env
    volumes:
      - ./keys/admin_private.pem:/app/keys/admin_private.pem:ro
      - ./keys/admin_public.pem:/app/keys/admin_public.pem:ro
    ports:
      - "50051:50051"
      - "50052:50052"

  runner:
    image: ftp-grpc-runner
    container_name: ftp-grpc-runner
    env_file:
      - ./client/.env
      - ./destination/.env
      - ./runner/.env
    volumes:
      - ./keys/admin_public.pem:/app/keys/admin_public.pem:ro
    ports:
      - "8081:8081"
      - "50053:50053"

  frontend:
    image: ftp-grpc-frontend
    container_name: ftp-grpc-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env

  mongoAdmin:
    image: mongo:7.0
    container_name: mongoAdmin
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - ./server/.env
    ports:
      - "27017:27017"
    volumes:
      - mongoAdminVolume:/data/db

  mongoBank:
    image: mongo:7.0
    container_name: mongoBank
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_BANK_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_BANK_PASSWORD}
    env_file:
      - ./runner/.env
    ports:
      - "27018:27017"
    volumes:
      - mongoBankVolume:/data/db

volumes:
  mongoAdminVolume:
  mongoBankVolume: