version: "3.9"

services:
  # ------------------ SERVER ------------------
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ftp-grpc-server
    env_file:
      - ./server/.env
    volumes:
      # - ./server/.env:/app/server/.env:ro
      - ./keys/admin_public.pem:/app/keys/admin_public.pem:ro
      - ./keys/admin_private.pem:/app/keys/admin_private.pem:ro
    ports:
      - "50051:50051"  
      - "50052:50052"  

  # ------------------ RUNNER ------------------
  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: ftp-grpc-runner
    depends_on:
      - server
    env_file:
      - ./client/.env
      - ./destination/.env
    volumes:
      - ./keys/admin_public.pem:/app/keys/admin_public.pem:ro
    ports:
      - "8081:8081"    
      - "50053:50053"  

  # ------------------ FRONTEND ------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend   
    container_name: ftp-grpc-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
