syntax = "proto3";

package ftp;

service TransferService {
    rpc Transfer (TransferRequest) returns (TransferResponse);
}

message TransferRequest {
    Metadata metadata = 1;
}

message Metadata {
    string transfer_id = 1;       
    string sender_bank_id = 2; // bank id
    string receiver_bank_id = 3; // receiver bank id

    oneof payload_type {
        FileInfo file_info = 4;      
        MessageInfo message_info = 5;
    }
}

message FileInfo {
    string name = 1;
    string path = 2;
    // uint64 size = 3; // Total size of the file in bytes
    // string content_type = 4; // e.g., "image/jpeg", "application/pdf"
}

message MessageInfo {
    uint64 length = 1; 
}

message TransferResponse {
    string transfer_id = 1; 
    Status status = 2;
    string message = 3;     // e.g., "Successfully received by B", "Forwarded to C", "Error: C unavailable"
}

enum Status {
    SUCCESS = 0; 
    // IN_PROGRESS = 1;                  
    FAILURE = 2;
}